In [148]:
import torch
import numpy as np
torch.random.manual_seed(0)

In [85]:
class MockModel(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.layer = torch.nn.Linear(3, 1, bias = False)
	
	def forward(self, x):
		return self.layer(x)

In [86]:
mm = MockModel()
print(mm.layer.weight)
print(mm.layer.weight.requires_grad)
print(mm.layer.weight.grad)

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752]], requires_grad=True)
True
None


In [171]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

In [172]:
print(x)
print(x.requires_grad)
print(x.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
False
None


In [194]:
class MockModel(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.layer = torch.nn.Linear(3, 2, bias = False)
	
	def forward(self, x):
		return self.layer(x)

In [196]:
mm = MockModel()
mm.layer.weight

torch.Size([2, 3])

In [173]:
layer = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float, requires_grad=True)
print(layer)
print(layer.requires_grad)
print(layer.grad)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)
True
None


In [174]:
# y = mm(x)
y = torch.matmul(x, layer)

In [175]:
print(y)
print(y.requires_grad)
print(y.grad)

tensor([[22., 28.],
        [49., 64.]], grad_fn=<MmBackward0>)
True
None


/tmp/ipykernel_2326648/61410144.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


In [176]:
loss = torch.nn.functional.cross_entropy(y, torch.tensor([0, 1]))

In [193]:
targets = torch.tensor([0, 1])
targets[0].view(1)

tensor([0])

In [177]:
print(loss)
print(loss.requires_grad)
print(loss.grad)

tensor(3.0012, grad_fn=<NllLossBackward0>)
True
None


/tmp/ipykernel_2326648/2363823690.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print(loss.grad)


In [178]:
loss.backward()

In [179]:
print(layer)
print(layer.requires_grad)
print(layer.grad)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], requires_grad=True)
True
tensor([[-0.4988,  0.4988],
        [-0.9975,  0.9975],
        [-1.4963,  1.4963]])


In [189]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
layer = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float, requires_grad=True)
y = torch.matmul(x, layer)
loss = torch.nn.functional.cross_entropy(y, torch.tensor([0, 1]))
loss.backward()
grad0 = layer.grad
print(grad0)

tensor([[-0.4988,  0.4988],
        [-0.9975,  0.9975],
        [-1.4963,  1.4963]])


In [2]:
import torch

In [4]:
torch.tensor([[1, 2], [3, 4], [5, 6]])[:3]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [186]:
x = torch.tensor([[1.0, 2.0, 3.0]])
layer = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float, requires_grad=True)
y = torch.matmul(x, layer)
loss = torch.nn.functional.cross_entropy(y, torch.tensor([0]))
loss.backward()
grad1 = layer.grad
print(grad1)

tensor([[-0.9975,  0.9975],
        [-1.9951,  1.9951],
        [-2.9926,  2.9926]])


In [187]:
x = torch.tensor([[4.0, 5.0, 6.0]])
layer = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float, requires_grad=True)
y = torch.matmul(x, layer)
loss = torch.nn.functional.cross_entropy(y, torch.tensor([1]))
loss.backward()
grad2 =layer.grad
print(grad2)

tensor([[ 1.2236e-06, -1.4305e-06],
        [ 1.5295e-06, -1.7881e-06],
        [ 1.8354e-06, -2.1458e-06]])


In [190]:
t1 = torch.tensor([[-0.9975,  0.9975],
        [-1.9951,  1.9951],
        [-2.9926,  2.9926]])
t2 = torch.tensor([[ 1.2236e-06, -1.4305e-06],
        [ 1.5295e-06, -1.7881e-06],
        [ 1.8354e-06, -2.1458e-06]])
(grad1 + grad2) / 2 == grad0

tensor([[True, True],
        [True, True],
        [True, True]])